name: CICD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          rm -rf dist
          npm ci
          npm run build --if-present
          git config --global init.defaultBranch main
          git config --global user.email "iljo.joseph.yoo@gmail.com"
          git config --global user.name "solduma"
          cd dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://solduma:${{ secrets.GITHUB_TOKEN }}@github.com:solduma/solduma.github.io.git main:gh-pages
