name: CICD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: git config --global init.defaultBranch main
      - run: git config --global user.email "iljo.joseph.yoo@gmail.com"
      - run: git config --global user.name "solduma"
      - run: ./deploy.sh
